name: Post JSON File to Two URLs
  
on:
  push:
    branches:
      - main # Runs only when pushing to the main branch
  workflow_dispatch: # Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
          curl -X POST "https://:E3Mx01MTRLG66_7vtrKaBg@eu.tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:2HZDWbf9RNyNzI99WXw8Ag/streams/AQAAADkTpetoKE7msSIYHoyNhwsAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json
    
      - name: Send JSON Data to Second URL
        run: |
          curl -X POST "https://:sH10AhZbRA2gURrX-EbZkQ@eu.tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:2HZDWbf9RNyNzI99WXw8Ag/streams/AQAAAKpR5kI230OWrKWxwSSap1UAAAAA" \
            -H "Content-Type: application/json" \
            -d @stream.json
